### ISSUE TITLE
Unable to create a new account

### ISSUE THREAD

**Issue by bjornthebear** [apaleslimghost/almanac#161]
Hello,

I just tried to set up an account on Almanac and it gave me the following error code:

Method 'createAccount' not found

Am I doing something wrong here?

**Comment by apaleslimghost** [comment]
sorry about that @bjornthebear, i recently released a large refactor so it's probably something i broke. i'll take a look into it this week

**Comment by apaleslimghost** [comment]
the fix for this is being released. sorry for the inconvenience! there's likely to be other rough edges, it's very much in beta for now

**Comment by bjornthebear** [comment]
No worries! Thank you!
