### ISSUE TITLE
Can't create new campaign

### ISSUE THREAD

**Issue by piersb** [apaleslimghost/almanac#64]
![screen shot 2018-01-10 at 18 04 03](https://user-images.githubusercontent.com/1419092/34787897-c33515fa-f630-11e7-8246-df167ef3c21c.png)

**Comment by piersb** [comment]
It's a problem with Safari: https://stackoverflow.com/questions/41028769/safari-is-saying-formdata-entries-is-not-a-function

**Comment by apaleslimghost** [comment]
we'll need a FormData polyfill for safari ([this one looks fine](https://github.com/jimmywarting/FormData)), or to change [`@quarterto/form-json`](https://gist.github.com/quarterto/7517213421e4694fda5f37cb96422ae1) to not use it

**Comment by piersb** [comment]
Currently attempting to install that very package. :)
