### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by apaleslimghost** [apaleslimghost/almanac#86]
Heroku can automate it all but it requires at least a Hobby dyno ($7/mo) https://devcenter.heroku.com/articles/automated-certificate-management 🤷‍♀️

**Comment by rowanbeentje** [comment]
I've used [greenlock-express](https://www.npmjs.com/package/greenlock-express) for this without any problems.

```
import expressHelper from 'greenlock-express';

export default expressApp => {
	if (process.env.NODE_ENV !== 'production') {
		const port = process.env.port || 3005;
		expressApp.listen(port);
		console.log(`Listening on port ${port}`);
		return;
	}

	// Create an instance of node-greenlock wrapping the passed-in Express app
	// (To regenerate certs delete the ~/letsencrypt cert store)
	expressHelper.create({
		server: 'https://acme-v01.api.letsencrypt.org/directory',
		agreeTos: true,
		email: 'FOO',
		approveDomains: [ 'BAR' ],
		app: expressApp,
		renewWithin: (60 * 24 * 60 * 60 * 1000),
	}).listen(80, 443);
}
```

**Comment by rowanbeentje** [comment]
(I think the prod switch is there because it contacts the domain to verify?)

**Comment by apaleslimghost** [comment]
pretty sure that won't work with meteor, there's no access to the underlying node server. there are a few meteor-specific things i've found that have some caveats:

- https://github.com/nolandg/meteor-lets-encrypt, doesn't automatically renew, requires filesystem access i don't think we can get on heroku
- https://github.com/zodern/meteor-up, deployment tool, docker based so we'd have to rethink heroku deployments (the horse buildpack Just Works 🤷‍♀️)

**Comment by rowanbeentje** [comment]
Ah meteor, soz 🤦‍♂️

**Comment by apaleslimghost** [comment]
yeah i've ponied up the cash for heroku to sort this out
